#!/bin/bash

set -e -o nounset

. ./.shell.sh

echo "Tagging new images"

for tag in alpine fedora centos ubuntu debian debian-slim minideb
do
  docker tag arduino:$tag $dckr_img:$tag
  docker push $dckr_img:$tag
done
unset tag

docker tag arduino:alpine $dckr_img:latest
docker push $dckr_img:latest

# Sign-off build
curl -sSf -X POST \
  "https://dotmpe.com/build.php?i=${BUILD_KEY}&TAGS=alpine;fedora;centos;debian;debian-slim;minideb&BUILD_ID=${BUILD_CODE}&END=$(urlsafe_datetime)" || echo "Sign-off failed"
