#!/bin/bash

set -e -o nounset

. ./.shell.sh
. ./vars.sh

mkdir -vp $PROJ_DIR/arduino-docs/Blink
curl -sSf \
  https://raw.githubusercontent.com/arduino/Arduino/master/build/shared/examples/01.Basics/Blink/Blink.ino \
  -o $PROJ_DIR/arduino-docs/Blink/Blink.ino


# Test initialization and compile
runtest()
{
  rm -rf $DCKR_VOL/arduino
  ./init.sh
  ./exec.sh compile -b arduino:avr:pro Blink
}

for tag in fedora centos
do
  echo "Testing arduino:$tag">&2
  export tag
  runtest || continue
done
unset tag

for tag in ubuntu debian debian-slim minideb
do
  echo "Testing arduino:$tag">&2
  export tag
  runtest || continue
done
unset tag

export tag=alpine shell=ash
echo "Testing arduino:$tag">&2
runtest
unset tag shell

#
